---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    env: dev
spec: 
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
          name: nginx_port